### ISSUE TITLE
ImportError: cannot import name build

### ISSUE THREAD

**Issue by Philipp97714** [gsuitedevs/python-samples#103]
## Expected Behavior
Getting no exception

## Actual Behavior
Getting an exception (line numbers are the same as here on GitHub)
```
ssh://pi@192.168.178.137:22/usr/bin/python -u /tmp/pycharm_project_397/demo/calendar.py
Traceback (most recent call last):
  File "/tmp/pycharm_project_397/demo/calendar.py", line 20, in <module>
    from googleapiclient.discovery import build
  File "/home/pi/.local/lib/python2.7/site-packages/googleapiclient/discovery.py", line 41, in <module>
    from email.generator import Generator as BytesGenerator
  File "/usr/lib/python2.7/email/generator.py", line 15, in <module>
    from email.header import Header
  File "/usr/lib/python2.7/email/header.py", line 16, in <module>
    import email.quoprimime
  File "/usr/lib/python2.7/email/quoprimime.py", line 49, in <module>
    from email.utils import fix_eols
  File "/usr/lib/python2.7/email/utils.py", line 32, in <module>
    from email._parseaddr import quote
  File "/usr/lib/python2.7/email/_parseaddr.py", line 16, in <module>
    import time, calendar
  File "/tmp/pycharm_project_397/demo/calendar.py", line 20, in <module>
    from googleapiclient.discovery import build
ImportError: cannot import name build

Process finished with exit code 1

```

## Steps to Reproduce the Problem

1. run pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
2. start quickstart.py

## Specifications

- Python version 2.7.13
- OS Raspbian

**Comment by erickoledadevrel** [comment]
Can you confirm that the `pip install` worked correctly? Were there any errors?

**Comment by Joshkmalone18** [comment]
I'm having a very similar issue. 
`  File "quickstart.py", line 19, in <module>
    from googleapiclient.discovery import build
  File "/Users/josh.malone/anaconda3/lib/python3.6/site-packages/googleapiclient/discovery.py", line 32, in <module>
    from six.moves import http_client
  File "/Users/josh.malone/anaconda3/lib/python3.6/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/Users/josh.malone/anaconda3/lib/python3.6/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/Users/josh.malone/anaconda3/lib/python3.6/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/Users/josh.malone/anaconda3/lib/python3.6/http/client.py", line 71, in <module>
    import email.parser
  File "/Users/josh.malone/anaconda3/lib/python3.6/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/Users/josh.malone/anaconda3/lib/python3.6/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/Users/josh.malone/anaconda3/lib/python3.6/email/_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "/Users/josh.malone/anaconda3/lib/python3.6/email/utils.py", line 33, in <module>
    from email._parseaddr import quote
  File "/Users/josh.malone/anaconda3/lib/python3.6/email/_parseaddr.py", line 16, in <module>
    import time, calendar
  File "/Users/josh.malone/PythonProjects/calendar.py", line 1, in <module>
    import requests
  File "/Users/josh.malone/anaconda3/lib/python3.6/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Users/josh.malone/anaconda3/lib/python3.6/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/Users/josh.malone/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/Users/josh.malone/anaconda3/lib/python3.6/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ImportError: cannot import name 'IncompleteRead'`

pip install works fine 

`pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
Requirement already up-to-date: google-api-python-client in /Users/josh.malone/anaconda3/lib/python3.6/site-packages (1.7.8)
Requirement already up-to-date: google-auth-httplib2 in /Users/josh.malone/anaconda3/lib/python3.6/site-packages (0.0.3)
Requirement already up-to-date: google-auth-oauthlib in /Users/josh.malone/anaconda3/lib/python3.6/site-packages (0.3.0)
Requirement already satisfied, skipping upgrade: uritemplate<4dev,>=3.0.0 in /Users/josh.malone/anaconda3/lib/python3.6/site-packages (from google-api-python-client) (3.0.0)
Requirement already satisfied, skipping upgrade: six<2dev,>=1.6.1 in /Users/josh.malone/anaconda3/lib/python3.6/site-packages (from google-api-python-client) (1.12.0)
Requirement already satisfied, skipping upgrade: google-auth>=1.4.1 in /Users/josh.malone/anaconda3/lib/python3.6/site-packages (from google-api-python-client) (1.6.3)
Requirement already satisfied, skipping upgrade: httplib2<1dev,>=0.9.2 in /Users/josh.malone/anaconda3/lib/python3.6/site-packages (from google-api-python-client) (0.12.3)
Requirement already satisfied, skipping upgrade: requests-oauthlib>=0.7.0 in /Users/josh.malone/anaconda3/lib/python3.6/site-packages (from google-auth-oauthlib) (1.2.0)
Requirement already satisfied, skipping upgrade: pyasn1-modules>=0.2.1 in /Users/josh.malone/anaconda3/lib/python3.6/site-packages (from google-auth>=1.4.1->google-api-python-client) (0.2.5)
Requirement already satisfied, skipping upgrade: rsa>=3.1.4 in /Users/josh.malone/anaconda3/lib/python3.6/site-packages (from google-auth>=1.4.1->google-api-python-client) (4.0)
Requirement already satisfied, skipping upgrade: cachetools>=2.0.0 in /Users/josh.malone/anaconda3/lib/python3.6/site-packages (from google-auth>=1.4.1->google-api-python-client) (3.1.0)
Requirement already satisfied, skipping upgrade: requests>=2.0.0 in /Users/josh.malone/anaconda3/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (2.21.0)
Requirement already satisfied, skipping upgrade: oauthlib>=3.0.0 in /Users/josh.malone/anaconda3/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.0.1)
Requirement already satisfied, skipping upgrade: pyasn1<0.5.0,>=0.4.1 in /Users/josh.malone/anaconda3/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.4.1->google-api-python-client) (0.4.4)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /Users/josh.malone/anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.0.4)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /Users/josh.malone/anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (1.22)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /Users/josh.malone/anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (2018.10.15)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /Users/josh.malone/anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (2.6)
`

**Comment by erickoledadevrel** [comment]
@Joshkmalone18 - From what I can tell the error has something to do with changes to the requests module, but I'm not sure exactly how to resolve it. You might want to try sing `pyenv` or `virtualenv` to create an isolated Python environment for your project, so there aren't any conflicts with other modules you have installed.

**Comment by nickrw** [comment]
I also encountered the same issue that @Philipp97714 did. It was because the file was named `calendar.py` - renaming it solved the problem.
