### ISSUE TITLE
SSL Certificate Verify Failed

### ISSUE THREAD

**Issue by lachlancahill** [gsuitedevs/python-samples#107]
## Expected Behavior
followed instructions on : 
https://developers.google.com/drive/api/v3/quickstart/python

and a similary quickstart guide for google sheets. 

The error occurs once the verification has been granted and the token.pickle has been created. 

## Actual Behavior
In python 3.4: 

Traceback (most recent call last):
  File "C:/Users/cahilll/PycharmProjects/GoogleAPI34/venv/quickstart.py", line 50, in <module>
    main()
  File "C:/Users/cahilll/PycharmProjects/GoogleAPI34/venv/quickstart.py", line 35, in main
    service = build('drive', 'v3', credentials=creds)
  File "C:\Users\cahilll\PycharmProjects\GoogleAPI34\venv\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\cahilll\PycharmProjects\GoogleAPI34\venv\lib\site-packages\googleapiclient\discovery.py", line 224, in build
    requested_url, discovery_http, cache_discovery, cache, developerKey)
  File "C:\Users\cahilll\PycharmProjects\GoogleAPI34\venv\lib\site-packages\googleapiclient\discovery.py", line 274, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "C:\Users\cahilll\PycharmProjects\GoogleAPI34\venv\lib\site-packages\httplib2\__init__.py", line 1926, in request
    cachekey,
  File "C:\Users\cahilll\PycharmProjects\GoogleAPI34\venv\lib\site-packages\httplib2\__init__.py", line 1595, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\cahilll\PycharmProjects\GoogleAPI34\venv\lib\site-packages\httplib2\__init__.py", line 1501, in _conn_request
    conn.connect()
  File "C:\Users\cahilll\PycharmProjects\GoogleAPI34\venv\lib\site-packages\httplib2\__init__.py", line 1291, in connect
    self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
  File "C:\Python34\lib\ssl.py", line 344, in wrap_socket
    _context=self)
  File "C:\Python34\lib\ssl.py", line 540, in __init__
    self.do_handshake()
  File "C:\Python34\lib\ssl.py", line 767, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)

in python 3.7: 
Traceback (most recent call last):
  File "C:/Users/cahilll/PycharmProjects/excelrefresher/venv/GoogleAPI.py", line 50, in <module>
    main()
  File "C:/Users/cahilll/PycharmProjects/excelrefresher/venv/GoogleAPI.py", line 34, in main
    service = build('drive', 'v3', credentials=creds)
  File "C:\Users\cahilll\PycharmProjects\excelrefresher\venv\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\cahilll\PycharmProjects\excelrefresher\venv\lib\site-packages\googleapiclient\discovery.py", line 224, in build
    requested_url, discovery_http, cache_discovery, cache, developerKey)
  File "C:\Users\cahilll\PycharmProjects\excelrefresher\venv\lib\site-packages\googleapiclient\discovery.py", line 274, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "C:\Users\cahilll\PycharmProjects\excelrefresher\venv\lib\site-packages\httplib2\__init__.py", line 1926, in request
    cachekey,
  File "C:\Users\cahilll\PycharmProjects\excelrefresher\venv\lib\site-packages\httplib2\__init__.py", line 1595, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\cahilll\PycharmProjects\excelrefresher\venv\lib\site-packages\httplib2\__init__.py", line 1501, in _conn_request
    conn.connect()
  File "C:\Users\cahilll\PycharmProjects\excelrefresher\venv\lib\site-packages\httplib2\__init__.py", line 1291, in connect
    self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
  File "C:\Users\cahilll\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Users\cahilll\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "C:\Users\cahilll\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)

## Steps to Reproduce the Problem

Follow steps in guide from google

## Specifications

- Python version  3.4 and 3.7 both detailed above. 
- OS - Windows 7 Professional.
- PyCharm 2018.3.5 (though same issue occurs when program run from cmd)

**Comment by asrivas** [comment]
It looks like you're having an issue with your SSL certs, the auth library in the quickstart just validates them. I would try fixing the cert, described similarly here:
https://stackoverflow.com/questions/49943410/pip-ssl-error-on-windows
then trying again.

**Comment by OneGneissGuy** [comment]
@asrivas I believe you are correct. In fact I am having this same issue ```ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)``` because I reside behind a MITM ssl firewall. While I can bypass this issue by passing the path to my certs file directly to `conda`, `pip` or `requests`  or by setting the library kwarg 'verify=false` , how would I do that using the gmail `quickstart.py` example code...where do I specify my certs file in this example?

**Comment by erickoledadevrel** [comment]
It's highly recommended that you keep SSL verification enabled, and find a way to correctly install the CA certs in your environment. That said, there is an existing issue on the client library's repo that discusses how you can disable SSL verification:

https://github.com/googleapis/google-api-python-client/issues/478#issuecomment-402054017

Please follow up there, as they are the experts in the underlying library.

**Comment by ManelBM** [comment]
Hello all, 
I have exactly the same issue than lachlancahill ... @lachlancahill  have you found a solution that worked for you ?

**Comment by lachlancahill** [comment]
I believe the issue was that the company network was stripping SSL certificates from web traffic. I suggest raising this with the entity's IT department. On 7/01/2021 2:26 am, ManelBM <notifications@github.com> wrote:
Hello all,
I have exactly the same issue than lachlancahill ... @lachlancahill  have you found a solution that worked for you ?
