### ISSUE TITLE
ImportError: cannot import name InstalledAppFlow

### ISSUE THREAD

**Issue by RenzoBertocchi** [gsuitedevs/python-samples#110]
## Expected Behavior

run

## Actual Behavior

Traceback (most recent call last):
  File "google.py", line 5, in <module>
    from google_auth_oauthlib.flow import InstalledAppFlow
  File "/Library/Python/2.7/site-packages/google_auth_oauthlib/flow.py", line 62, in <module>
    import google.oauth2.credentials
  File "/Library/Python/2.7/site-packages/google/oauth2/credentials.py", line 42, in <module>
    from google.oauth2 import _client
  File "/Library/Python/2.7/site-packages/google/oauth2/_client.py", line 35, in <module>
    from google.auth import jwt
  File "/Library/Python/2.7/site-packages/google/auth/jwt.py", line 53, in <module>
    from google.auth import _service_account_info
  File "/Library/Python/2.7/site-packages/google/auth/_service_account_info.py", line 22, in <module>
    from google.auth import crypt
  File "/Library/Python/2.7/site-packages/google/auth/crypt/__init__.py", line 39, in <module>
    from google.auth.crypt import rsa
  File "/Library/Python/2.7/site-packages/google/auth/crypt/rsa.py", line 27, in <module>
    from google.auth.crypt import _python_rsa
  File "/Users/mrcsvberto/google.py", line 5, in <module>
    from google_auth_oauthlib.flow import InstalledAppFlow
ImportError: cannot import name InstalledAppFlow

## Steps to Reproduce the Problem

python quickstart.py

## Specifications

- Python version 2.7.14
- OS Mac and Linux

**Comment by asrivas** [comment]
Which quickstart is this for? 
Were you able to install the required libraries?
See step 2 in this quickstart:
https://developers.google.com/drive/api/v3/quickstart/python

pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

**Comment by RenzoBertocchi** [comment]
Did all steps but got that error following this:
https://developers.google.com/admin-sdk/directory/v1/quickstart/python

**Comment by asrivas** [comment]
Can you try installing pyopenssl?
https://stackoverflow.com/questions/14063124/importerror-cannot-import-name-signedjwtassertioncredentials

**Comment by successanil** [comment]
Hi . 
I am also getting the same error when I am using python script to upload file to google drive..
Few months back it used to work.

**Comment by samavan** [comment]
Same error...
All installed properly but still...
@asrivas installed pyopenssl as mentioned but still :( 
![install1](https://user-images.githubusercontent.com/6184992/80857412-2bfc2680-8c7c-11ea-8b5f-041fc597cb81.JPG)
![error1](https://user-images.githubusercontent.com/6184992/80857413-2dc5ea00-8c7c-11ea-8508-28d6e4c87205.JPG)

Using pycharm.

**Comment by Marcustks** [comment]
Pls, try this
pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

**Comment by stakepool247** [comment]
same error:
    from google_auth_oauthlib.flow import InstalledAppFlowp
ImportError: cannot import name 'InstalledAppFlowp' from 'google_auth_oauthlib.flow'

**Comment by reactor-17** [comment]
Yep, getting this error as well, it works when running locally, but not when on the cloud. I've installed and update everything and followed the documentation.

**Comment by reactor-17** [comment]
Actually, I ran the command `pip3 install google-auth-oauthlib` and the error disappeared!

**Comment by Felix-Fang** [comment]
It's possible there are multiple versions of python installed. You could try: `python3.9 -m pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib`. Python3.9 as an example.

**Comment by victory032** [comment]
Please let me know that how to resolve this issue.

Traceback (most recent call last):
  File "E:\Project\loyverse+gpt\main.py", line 16, in <module>
    flow = InstalledAppFlow.from_client_secrets_file(
NameError: name 'InstalledAppFlow' is not defined
