### ISSUE TITLE
Google Sheets API - Python Quickstart not working

### ISSUE THREAD

**Issue by kevinpz** [gsuitedevs/python-samples#113]
Hi!

I'm trying to follow the quickstart guide to use the Google Sheets API with Python 3, but the code fails each time.

Guide: https://developers.google.com/sheets/api/quickstart/python

## Expected Behavior
The code should exit without error.

## Actual Behavior
The code crashes.

```
python3 quickstart.py
Please visit this URL to authorize this application: https://accounts.google.com/o/XXXXXXXX
Traceback (most recent call last):
  File "quickstart.py", line 70, in <module>
    main()
  File "quickstart.py", line 48, in main
    creds = flow.run_local_server()
  File "/usr/local/lib/python3.7/site-packages/google_auth_oauthlib/flow.py", line 420, in run_local_server
    self.fetch_token(authorization_response=authorization_response)
  File "/usr/local/lib/python3.7/site-packages/google_auth_oauthlib/flow.py", line 241, in fetch_token
    self.client_config['token_uri'], **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 208, in fetch_token
    state=self._state)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/web_application.py", line 203, in parse_request_uri_response
    response = parse_authorization_code_response(uri, state=state)
  File "/usr/local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 268, in parse_authorization_code_response
    raise MissingCodeError("Missing code parameter in response.")
oauthlib.oauth2.rfc6749.errors.MissingCodeError: (missing_code) Missing code parameter in response.
```

## Steps to Reproduce the Problem

1. Download the `quickstart.py` file
2. Run `python3 quickstart.py`
3. Login on the google chrome page, and accept all
4. The python crashes

I've also tried with python2, but I have the same result.

## Specifications

- Python version (`python --version`): Python 3.7.3
- OS (Mac/Linux/Windows): macOS 10.14.5

**Comment by kevinpz** [comment]
Hi!

So this was not related to the code. It seems that my Chrome had some remaining of a web app that was running on port 8080 (same port used by the oauth flow).

I had to click on Developer tools -> Application -> Clear storage -> Clear site data to clean it.

Now everything is working well!
