### ISSUE TITLE
quickstart.py fails on error: No such file or directory: 'credentials.json'

### ISSUE THREAD

**Issue by tenleftfingers** [gsuitedevs/python-samples#134]
## Expected Behavior
Browser window should open requesting authorisation

## Actual Behavior
No browser opens. Error logged to console:
$ python quickstart.py 
Traceback (most recent call last):
  File "quickstart.py", line 52, in <module>
    main()
  File "quickstart.py", line 29, in main
    'credentials.json', SCOPES)
  File "/home/iarla/civetweb-instance-cal/cal/local/lib/python2.7/site-packages/google_auth_oauthlib/flow.py", line 196, in from_client_secrets_file
    with open(client_secrets_file, 'r') as json_file:
IOError: [Errno 2] No such file or directory: 'credentials.json'

## Steps to Reproduce the Problem

1. run python quickstart.py as instructed in documentation https://developers.google.com/calendar/quickstart/python
2. Observer no browser appears
3. Observer error in terminal

## Specifications

- Python version: 2.7.12
- OS : Linux
- google-auth-oauthlib version: 0.4.1

**Comment by sqrrrl** [comment]
Did you complete step 1 correctly and save the file as instructed?

**Comment by darrenlimweiyang** [comment]
@tenleftfingers It seems like you did not add the credentials.json file into working directory as instructed?

**Comment by tenleftfingers** [comment]
I was sure I put it in the right place, but I'll try again and come back (can't get to it this week). Thank you. 

Seolta ó mo iPhone

**Comment by Devarsh-leo** [comment]
i am also facing the same issue when  i developed a python script it worked and now i am opening it after few months it is showing:
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'

is there anyway to regenerate the credential ?

**Comment by Devarsh-leo** [comment]
**[solved]** I provided full path of credential and it worked. i guess my editor has parent folder of my project as its main folder.

**Comment by shewitt-au** [comment]
I am also having this issue. The first comment in this ticket says the following:
 "Did you complete step 1 correctly and save the file as instructed?"

Step one is "To install the Google client library for Python". I see no instructions to save a file.
Am I missing something here?

**Comment by rachelhadad** [comment]
I was having the same problem. It looks like it's in the Prerequisites step now. On the Python Quickstart instructions page, https://developers.google.com/sheets/api/quickstart/python?authuser=3:

Underneath the note box that reads, "Note: For this quickstart, you are enabling the 'Google Sheets API'." is a bullet point that reads, "Authorization credentials for a desktop application. To create credentials for a desktop application, refer to Create credentials." With a link on the last two words, "Create credentials." This will take you to another page with some instructions that will eventually create the JSON file. Be sure to rename the file once it's downloaded to credentials.json.

**Comment by xutiann** [comment]
I'm having the same problem and I already rename the json file to credentials.json but it still shows the error

**Comment by rachelhadad** [comment]
It sounds like the computer can't find it, so it's likely in the wrong folder. Make sure it's in the working directory or that you change the filepath to wherever it's saved on your computer.

**Comment by xutiann** [comment]
How do know where is my working directory?

**Comment by antoineneidecker** [comment]
See this https://developers.google.com/workspace/guides/create-credentials?authuser=3

**Comment by ntraut** [comment]
I read the instructions from the page and it is written:

> 2. (optional). If this is your first time running the sample, the sample opens a new window prompting you to authorize access to your data:
> 
> If you are not already signed in to your Google account, you are prompted to sign in. If you are signed in to multiple Google accounts, you are asked to select one account to use for the authorization.
> 
> Note: Authorization information is stored on the file system, so subsequent executions don't prompt for authorization.
> 
> Click Accept. The app is authorized to access your data.
> 

Are those instructions outdated or am I missing something?

**Comment by github-canadianlad** [comment]
Alright, I figured it out. You need to jump a few hoops to download the JSON file (Remember to rename it to credentials.json)

1) Go to this link https://console.cloud.google.com/
2) Create credential from

> I was having the same problem. It looks like it's in the Prerequisites step now. On the Python Quickstart instructions page, https://developers.google.com/sheets/api/quickstart/python?authuser=3:
> 
> Underneath the note box that reads, "Note: For this quickstart, you are enabling the 'Google Sheets API'." is a bullet point that reads, "Authorization credentials for a desktop application. To create credentials for a desktop application, refer to Create credentials." With a link on the last two words, "Create credentials." This will take you to another page with some instructions that will eventually create the JSON file. Be sure to rename the file once it's downloaded to credentials.json.

Follows this guy's step

**Comment by GaoxieNju** [comment]
![image](https://user-images.githubusercontent.com/33541982/144239722-54df9a86-6f6c-4e32-8e55-9dc14d230559.png)
download the file and rename

**Comment by biduradhikari** [comment]
Rather than hard coding the path names (which change if you copy the file elsewhere), you should try getting the current directory path. Changing the code from line 31 as follows should solve the issue.

`            CURR_DIR = os.path.dirname(os.path.realpath(__file__))
            credential_file=str(CURR_DIR)+'/credentials.json'  # may need a backslash for windows, not sure.
            flow = InstalledAppFlow.from_client_secrets_file(
                credential_file, SCOPES)`

**Comment by Aran77** [comment]
if you rename the file to Credentials.json in windows you will find the name will be credentials.json.json in the cli window. 
rename the file to credentials.json in cli.

**Comment by MartianTribe** [comment]
I resolved this by simply pointing to the full path for the file: 

credsPath = os.path.expanduser("~/Desktop/Kargo/Development/Python/KargoPy/modules/credentials.json")
