### ISSUE TITLE
Python Quickstart - GSuite Admin SDK

### ISSUE THREAD

**Issue by wellskb** [gsuitedevs/python-samples#143]
Anyone could help me with this issue? I am running the Python quickstart and through this error below. Looks like that the library discovery doesn't exist. Anyone could explain me why? Thank a lot in advance.

## Expected Behavior
Create token.pickle after authentication

## Actual Behavior
Giving this error:

Traceback (most recent call last):
  File "token.py", line 2, in <module>
    from googleapiclient import discovery
  File "/venv/lib/python3.7/site-packages/googleapiclient/__init__.py", line 18, in <module>
    import logging
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections.abc
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/traceback.py", line 5, in <module>
    import linecache
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 35, in <module>
    from token import *
  File "/agent/autoconfigurations/gsuite/token.py", line 2, in <module>
    from googleapiclient import discovery
  File "/venv/lib/python3.7/site-packages/googleapiclient/discovery.py", line 56, in <module>
    from googleapiclient import _auth
  File "/venv/lib/python3.7/site-packages/googleapiclient/_auth.py", line 20, in <module>
    import google.auth
  File "/venv/lib/python3.7/site-packages/google/auth/__init__.py", line 19, in <module>
    from google.auth._default import default
  File "/venv/lib/python3.7/site-packages/google/auth/_default.py", line 30, in <module>
    import google.auth.transport._http_client
  File "/venv/lib/python3.7/site-packages/google/auth/transport/_http_client.py", line 27, in <module>
    _LOGGER = logging.getLogger(__name__)
AttributeError: module 'logging' has no attribute 'getLogger'

## Steps to Reproduce the Problem

1. Just run the Python quickstart and through this error.

## Specifications

- Python version (`python 3.x`)
- OS (Mac)

**Comment by sqrrrl** [comment]
Looks like you named the quickstart token.py. Unfortunately that's also the name of a built-in python library module, and that's causing things to fail.

Rename the file so it doesn't conflict.
