### ISSUE TITLE
quickstart.py: Client secrets must be for a web or installed app.

### ISSUE THREAD

**Issue by TimurNurlygayanov** [gsuitedevs/python-samples#158]
## Steps to Reproduce the Problem

1. Create Service account and download JSON file with credentials
2. Run quickstart.py

## Expected Behavior
The script works just fine, everything works from the box.

## Actual Behavior
The traceback:
```
    Traceback (most recent call last):
  File "google_docs.py", line 46, in <module>
    main()
  File "google_docs.py", line 31, in main
    'credentials.json', SCOPES)
  File "/usr/local/lib/python3.7/site-packages/google_auth_oauthlib/flow.py", line 199, in from_client_secrets_file
    return cls.from_client_config(client_config, scopes=scopes, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google_auth_oauthlib/flow.py", line 159, in from_client_config
    'Client secrets must be for a web or installed app.')
ValueError: Client secrets must be for a web or installed app.
```

## Specifications
- Python version
Python 3.7.4
- OS: Mac

Workaround:
The workaround I've found for this issue:
https://stackoverflow.com/a/61892378/7856072
(this workaround proves that credentials.json is the correct file for authorization and account has all necessary rights).

**Comment by aleonccc** [comment]
Hi there!
I followed all steps to run quickstart.py but it shows this output:
```
Traceback (most recent call last):
  File "C:\Users\aleon\Documents\lab\python\CRM_SUB\script\quickstart.py", line 57, in <module>
    main()
  File "C:\Users\aleon\Documents\lab\python\CRM_SUB\script\quickstart.py", line 30, in main
    flow = InstalledAppFlow.from_client_secrets_file(
  File "C:\Users\aleon\Documents\lab\python\CRM_SUB\script\venv\lib\site-packages\google_auth_oauthlib\flow.py", line 201, in from_client_secrets_file
    return cls.from_client_config(client_config, scopes=scopes, **kwargs)
  File "C:\Users\aleon\Documents\lab\python\CRM_SUB\script\venv\lib\site-packages\google_auth_oauthlib\flow.py", line 159, in from_client_config
    raise ValueError("Client secrets must be for a web or installed app.")
ValueError: Client secrets must be for a web or installed app.
```
Where could I download the credentials.json from?

**Comment by sidharthvijayakumar** [comment]
I am getting the same error I have downloaded the service account from my project and trying to delete my older emails. Can someone help me understand what I am doing wrong here ?
