### ISSUE TITLE
Access Not Configured...?

### ISSUE THREAD

**Issue by mgbvox** [gsuitedevs/python-samples#17]
Here's the full error text:
"
Getting the upcoming 10 events
Traceback (most recent call last):
  File "quickstart.py", line 25, in <module>
    orderBy='startTime').execute()
  File "/Users/mgb/anaconda3/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/mgb/anaconda3/lib/python3.6/site-packages/googleapiclient/http.py", line 842, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/calendar/v3/calendars/primary/events?timeMin=2018-07-19T12%3A49%3A23.839265Z&maxResults=10&singleEvents=true&orderBy=startTime&alt=json returned "Access Not Configured. Calendar API has not been used in project 253222910799 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/calendar.googleapis.com/overview?project=253222910799 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.">
"

**Comment by erickoledadevrel** [comment]
Did you use the "Enable the Google Calendar API" button in the quickstart instructions to create your `credentials.json` file? When you follow the link in the error message, does it show the Calendar API as enabled?

**Comment by mgbvox** [comment]
If instead I just name the project "New Project" and name the PRODUCT "Google Calendar API Quickstart," I get thru to the credentials json download page. But when I move it to my working directory, delete the old token from my prior auth, and re-authenticate with the new credentials, I get the same error:

"
Authentication successful.
Getting the upcoming 10 events
Traceback (most recent call last):
  File "quickstart.py", line 25, in <module>
    orderBy='startTime').execute()
  File "/Users/mgb/anaconda3/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/mgb/anaconda3/lib/python3.6/site-packages/googleapiclient/http.py", line 842, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/calendar/v3/calendars/primary/events?timeMin=2018-07-19T13%3A27%3A42.206230Z&maxResults=10&singleEvents=true&orderBy=startTime&alt=json returned "Access Not Configured. Calendar API has not been used in project 945003221313 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/calendar.googleapis.com/overview?project=945003221313 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.">

**Comment by erickoledadevrel** [comment]
I've been able to confirm three issues:

1. The "Enable" button in the quickstart is failing to actually enable the API. I've escalated this to the corresponding engineering team. In the mean time, you can click the link for the API Console and manually search for an enable the API.
2. The link in the error message isn't correct. It's linking you to a page for calendar.googleapis.com when it should be calendar-json.googleapis.com. I have to look into this further.
3. The Quickstart instructions recommend you name the project with "Google" in the project name, which is disallowed by policy. I'll update the instructions to remove that.

**Comment by mgbvox** [comment]
@erickoledadevrel , thank you! I'll check back tomorrow.
