### ISSUE TITLE
'Error opening file', 'credentials.json'

### ISSUE THREAD

**Issue by poirier** [gsuitedevs/python-samples#25]
Running the quickstart sample for the first time, from the instructions I expected it to open a browser window for me to authenticate myself. Instead I got the following tracebacks:

```Output:

$ python sheets.py
/home/poirier/.virtualenvs/pdfextract/lib/python3.7/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access token.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
Traceback (most recent call last):
  File "/home/poirier/.virtualenvs/pdfextract/lib/python3.7/site-packages/oauth2client/clientsecrets.py", line 121, in _loadfile
    with open(filename, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sheets.py", line 14, in <module>
    flow = client.flow_from_clientsecrets('credentials.json', SCOPES)
  File "/home/poirier/.virtualenvs/pdfextract/lib/python3.7/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/poirier/.virtualenvs/pdfextract/lib/python3.7/site-packages/oauth2client/client.py", line 2135, in flow_from_clientsecrets
    cache=cache)
  File "/home/poirier/.virtualenvs/pdfextract/lib/python3.7/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "/home/poirier/.virtualenvs/pdfextract/lib/python3.7/site-packages/oauth2client/clientsecrets.py", line 125, in _loadfile
    exc.strerror, exc.errno)
oauth2client.clientsecrets.InvalidClientSecretsError: ('Error opening file', 'credentials.json', 'No such file or directory', 2)
```

**Comment by erickoledadevrel** [comment]
The error indicates that it can't find the `credentials.json` file downloaded in Step 1. Can you ensure it's in the same directory?

**Comment by poirier** [comment]
I missed step 1c in the instructions.
