### ISSUE TITLE
ConnectionResetError: [WinError 10054] connection fail

### ISSUE THREAD

**Issue by fanhegang** [gsuitedevs/python-samples#31]
I want to get google calendar's information that is a project of used by python.
I prepared something that from google calendar API 's guide.
when executive then project , I got a error:
ConnectionResetError: [WinError 10054] 既存の接続はリモート ホストに強制的に切断されました。

The environment:
python version 3.6.1
windows 10
google chrome  68.0.3440.106（Official Build） （64bit）
※ I'm using a  proxy to access google

The error detail information
```
_>python quickstart.py
E:\Users\123456789\AppData\Local\Programs\Python\Python36\lib\site-packages\oauth2client\_helpers.py:255: UserWarning: Cannot access token.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?client_id=135970666564-rvv4lt7i90p10tcnhe8p7igmgrfkpkb0.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar.readonly&access_type=offline&response_type=code

If your browser is on a different machine then exit and re-run this
application with the command-line parameter

  --noauth_local_webserver

Traceback (most recent call last):
  File "quickstart.py", line 36, in <module>
    main()
  File "quickstart.py", line 18, in main
    creds = tools.run_flow(flow, store)
  File "E:\Users\123456789\AppData\Local\Programs\Python\Python36\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "E:\Users\123456789\AppData\Local\Programs\Python\Python36\lib\site-packages\oauth2client\tools.py", line 243, in run_flow
    credential = flow.step2_exchange(code, http=http)
  File "E:\Users\123456789\AppData\Local\Programs\Python\Python36\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "E:\Users\123456789\AppData\Local\Programs\Python\Python36\lib\site-packages\oauth2client\client.py", line 2054, in step2_exchange
    http, self.token_uri, method='POST', body=body, headers=headers)
  File "E:\Users\123456789\AppData\Local\Programs\Python\Python36\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "E:\Users\123456789\AppData\Local\Programs\Python\Python36\lib\site-packages\httplib2\__init__.py", line 1514, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "E:\Users\123456789\AppData\Local\Programs\Python\Python36\lib\site-packages\httplib2\__init__.py", line 1264, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "E:\Users\123456789\AppData\Local\Programs\Python\Python36\lib\site-packages\httplib2\__init__.py", line 1187, in _conn_request
    conn.connect()
  File "E:\Users\123456789\AppData\Local\Programs\Python\Python36\lib\site-packages\httplib2\__init__.py", line 1050, in connect
    raise socket_err
  File "E:\Users\123456789\AppData\Local\Programs\Python\Python36\lib\site-packages\httplib2\__init__.py", line 1013, in connect
    self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
  File "E:\Users\123456789\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "E:\Users\123456789\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "E:\Users\123456789\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "E:\Users\123456789\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 既存の接続はリモート ホストに強制的に切断されました。_
```

**Comment by grant** [comment]
It looks like there is a `ConnectionResetError` that may be from an issue with the proxy.

Can you try without using a proxy?
Or perhaps retry the request multiple times like [in this example](https://stackoverflow.com/a/39288941/1233286)?

@asrivas Can you follow-up on this issue?

**Comment by fanhegang** [comment]
I can't connect google's service without using a proxy, because I'm in China, and the proxy server is in Japan. that is normally, explore internet(google's calendar too) with use the proxy  except this issue.

**Comment by grant** [comment]
OK. I don't think we support proxies in our samples currently.

@asrivas Can you follow-up or unassign yourself from this issue?

**Comment by fanhegang** [comment]
Under your guidance, I rewrote the following code and solved the issue, although it's not fundamentally resolved。

File  "E:\Users\123456789\AppData\Local\Programs\Python\Python36\lib\site-packages\httplib2\\_\_init\_\_.py"

![image](https://user-images.githubusercontent.com/42328578/45738650-a43ae300-bc23-11e8-8b52-1053db10774a.png)

Thank you very much！！

**Comment by grant** [comment]
Glad it worked out!
