### ISSUE TITLE
Error while using this is python( django )

### ISSUE THREAD

**Issue by masterdungeon** [gsuitedevs/python-samples#35]
```
usage: manage.py [--auth_host_name AUTH_HOST_NAME] [--noauth_local_webserver]
                 [--auth_host_port [AUTH_HOST_PORT [AUTH_HOST_PORT ...]]]
                 [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
manage.py: error: unrecognized arguments: runserver
Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/rohit/django/env/lib/python3.5/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/rohit/django/env/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/home/rohit/django/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/home/rohit/django/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/rohit/django/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/home/rohit/django/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/rohit/django/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/home/rohit/django/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/rohit/django/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/home/rohit/django/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/rohit/django/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/home/rohit/django/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/rohit/django/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/home/rohit/django/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/rohit/django/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/home/rohit/django/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/rohit/django/env/lib/python3.5/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/home/rohit/django/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/rohit/django/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rohit/django/project/calender/views.py", line 23, in main
    creds = tools.run_flow(flow, store)
  File "/home/rohit/django/env/lib/python3.5/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/rohit/django/env/lib/python3.5/site-packages/oauth2client/tools.py", line 194, in run_flow
    flags = argparser.parse_args()
  File "/usr/lib/python3.5/argparse.py", line 1738, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/lib/python3.5/argparse.py", line 2394, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/usr/lib/python3.5/argparse.py", line 2381, in exit
    _sys.exit(status)
SystemExit: 2
```
While working this with in python (django) it says:
A server error occurred.  Please contact the administrator.
and also `Instance of 'Resource' has no 'events' member
`

**Comment by grant** [comment]
Can you fill out the issue template that we provided? Which sample is this?

**Comment by erickoledadevrel** [comment]
It looks like you aren't using one of our samples as-is, but instead created your own application in Django, so we wouldn't be able to reproduce the issue. For general developer support with the Calendar API please see the support options listed here: 

https://developers.google.com/calendar/support
