### ISSUE TITLE
SSL Cirtification Issue - For Google Drive API

### ISSUE THREAD

**Issue by Aniket1492** [gsuitedevs/python-samples#56]
## Expected Behavior
I am Following This Doc: https://developers.google.com/drive/api/v3/quickstart/python

## Actual Behavior
I am Getting the error like : 
Traceback (most recent call last):
  File "C:\Aniket\Python\Upload File to google Drive\quickstart.py", line 36, in <module>
    main()
  File "C:\Aniket\Python\Upload File to google Drive\quickstart.py", line 20, in main
    creds = tools.run_flow(flow, store)
  File "C:\Python35\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Python35\lib\site-packages\oauth2client\tools.py", line 243, in run_flow
    credential = flow.step2_exchange(code, http=http)
  File "C:\Python35\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Python35\lib\site-packages\oauth2client\client.py", line 2054, in step2_exchange
    http, self.token_uri, method='POST', body=body, headers=headers)
  File "C:\Python35\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Python35\lib\site-packages\httplib2\__init__.py", line 1924, in request
    cachekey,
  File "C:\Python35\lib\site-packages\httplib2\__init__.py", line 1595, in _request
    conn, request_uri, method, body, headers
  File "C:\Python35\lib\site-packages\httplib2\__init__.py", line 1501, in _conn_request
    conn.connect()
  File "C:\Python35\lib\site-packages\httplib2\__init__.py", line 1291, in connect
    self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
  File "C:\Python35\lib\ssl.py", line 377, in wrap_socket
    _context=self)
  File "C:\Python35\lib\ssl.py", line 752, in __init__
    self.do_handshake()
  File "C:\Python35\lib\ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Python35\lib\ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Python version (`3.5`)
- OS (Windows)

**Comment by erickoledadevrel** [comment]
This error usually indicates that the SSL certificates aren't configured correctly in your environment. Please take a look at this issue:

https://github.com/googleapis/google-api-python-client/issues/453
