### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by ZxBiohazardZx** [gsuitedevs/python-samples#68]
## Expected Behavior
Succesful login & returning sheet data

## Actual Behavior
TypeError: a bytes-like object is required, not 'str'
## Steps to Reproduce the Problem

1. Follow steps in QuickSetup
2. Run Quickstart.py

## Specifications
Propt returns : 
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?client_id=291562245980-3gqtl3pdj5da5ilhgfqupv1bq5166ei2.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2
Fauth%2Fspreadsheets.readonly&access_type=offline&response_type=code

If your browser is on a different machine then exit and re-run this
application with the command-line parameter

  --noauth_local_webserver

Exception happened during processing of request from ('127.0.0.1', 63178)
Traceback (most recent call last):
  File "C:\Users\Alex Vermeulen\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Alex Vermeulen\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 344, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\Alex Vermeulen\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Alex Vermeulen\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 717, in __init__
    self.handle()
  File "C:\Users\Alex Vermeulen\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 426, in handle
    self.handle_one_request()
  File "C:\Users\Alex Vermeulen\AppData\Local\Programs\Python\Python37-32\lib\http\server.py", line 414, in handle_one_request
    method()
  File "C:\Users\Alex Vermeulen\PycharmProjects\S1ImageFactory\venv\lib\site-packages\oauth2client\tools.py", line 100, in do_GET
    s.wfile.write("<html><head><title>Authentication Status</title></head>")
  File "C:\Users\Alex Vermeulen\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 796, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'

Authentication has failed: invalid_client

- Python version (`python --version`) 3.7
- OS (Mac/Linux/Windows) Windows

**Comment by ZxBiohazardZx** [comment]
when taking the "latest"  edition from this github sheets/quickstart.py i get: 

(venv) C:\Users\Alex Vermeulen\PycharmProjects\S1ImageFactory>quickstart.py
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=291562245980-3gqtl3pdj5da5ilhgfqupv1bq5166ei2.apps.googleusercontent.com&redirect_uri=http%
3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fspreadsheets.readonly&state=yDl3qCeMvvVpSEfMpeVcqKpLVNKeqg&access_type=offline
Traceback (most recent call last):
  File "C:\Users\Alex Vermeulen\PycharmProjects\S1ImageFactory\quickstart.py", line 70, in <module>
    main()
  File "C:\Users\Alex Vermeulen\PycharmProjects\S1ImageFactory\quickstart.py", line 48, in main
    creds = flow.run_local_server()
  File "C:\Users\Alex Vermeulen\PycharmProjects\S1ImageFactory\venv\lib\site-packages\google_auth_oauthlib\flow.py", line 420, in run_local_server
    self.fetch_token(authorization_response=authorization_response)
  File "C:\Users\Alex Vermeulen\PycharmProjects\S1ImageFactory\venv\lib\site-packages\google_auth_oauthlib\flow.py", line 241, in fetch_token
    self.client_config['token_uri'], **kwargs)
  File "C:\Users\Alex Vermeulen\PycharmProjects\S1ImageFactory\venv\lib\site-packages\requests_oauthlib\oauth2_session.py", line 307, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\Users\Alex Vermeulen\PycharmProjects\S1ImageFactory\venv\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 415, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "C:\Users\Alex Vermeulen\PycharmProjects\S1ImageFactory\venv\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "C:\Users\Alex Vermeulen\PycharmProjects\S1ImageFactory\venv\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 432, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "C:\Users\Alex Vermeulen\PycharmProjects\S1ImageFactory\venv\lib\site-packages\oauthlib\oauth2\rfc6749\errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientError: (invalid_client) Unauthorized



Still unable to get the sheet data

**Comment by ZxBiohazardZx** [comment]
Issue is resolved by taking the following steps: 

1) removing all API client keys
2) Manually creating a new Client-ID OAUTH : Type: Other, Projectname: Quickstart
3) Manually enter the information presented into a pre-downloaded JSON (removing spaces etc)
4) Program works as intended.

Not really sure what is causing this but apparently it is not directly related to the code provided here.
