### ISSUE TITLE
UnicodeDecodeError in Google Sheets API Quickstart

### ISSUE THREAD

**Issue by ahmibrahim97** [gsuitedevs/python-samples#97]
## Expected Behavior
working quickstart

## Actual Behavior
Traceback (most recent call last):
  File "quickstart.py", line 55, in <module>
    main()
  File "quickstart.py", line 32, in main
    'credentials.json', SCOPES)
  File "/anaconda3/lib/python3.7/site-packages/google_auth_oauthlib/flow.py", line 172, in from_client_secrets_file
    client_config = json.load(json_file)
  File "/anaconda3/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/anaconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 41: invalid continuation byte

## Steps to Reproduce the Problem

1. Follow the quickstart steps from the Google Sheets API page for python
2. run: python quickstart.py
3. Observe Error

## Specifications

- Python version (`python --version`): 3.71
- OS (Mac/Linux/Windows): Mac

**Comment by sqrrrl** [comment]
Can you verify the content of the credentials.json file? Sounds like there's a unexpected character somewhere in there, but would need more info to narrow down the problem. Can you share the client_id, project_id, and redirect_uris fields from it?

**Comment by erickoledadevrel** [comment]
Closing due to inactivity.
